name: Continue On Error Test

on:
  workflow_dispatch:

jobs:
  testing_errors:
    name: Testing Error Continuation
    runs-on: ubuntu-latest
    steps:
      - name: Scenario 1 - Throw Error As Expected
        id: scen-1
        continue-on-error: true
        run: exit 1

      - name: Scenario 2 - Output After Error
        id: scen-2
        continue-on-error: true
        run: |
          set +e
          blah
          echo "Test"

      - name: Scenario 3 - Output after error w/o continue-on-error
        id: scen-3
        run: |
          set +e
          blah
          echo "Test 2"
          echo "scenario_3_failure=true" >> ${GITHUB_OUTPUT}

      - name: Scenario 4 - Output after error w/ continue-on-error and no set+e
        id: scen-4
        continue-on-error: true
        run: |
          blah
          echo "Test 3"

      - name: Scenario 5 - Exit 1 with set +e
        continue-on-error: true
        id: scen-5
        run: |
          set +e
          echo "Test 5"
          exit 1

      - name: Run If Scenario 3 Has Failed
        id: fail-scen-3-test
        if: ${{ steps.scen-3.outputs.scenario_3_failure }}
        run: echo "Scenario 3 has failed. Outputting error to summary." >> ${GITHUB_STEP_SUMMARY}

      - name: Display Outcomes and Conclusions of each Scenario
        id: output-scenario-results
        run: |
          echo "Scenario 1 outcome: ${{ steps.scen-1.outcome }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 1 conclusion: ${{ steps.scen-1.conclusion }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 2 outcome: ${{ steps.scen-2.outcome }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 2 conclusion: ${{ steps.scen-2.conclusion }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 3 outcome: ${{ steps.scen-3.outcome }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 3 conclusion: ${{ steps.scen-3.conclusion }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 4 outcome: ${{ steps.scen-4.outcome }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 4 conclusion: ${{ steps.scen-4.conclusion }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 5 outcome: ${{ steps.scen-5.outcome }}" >> ${GITHUB_STEP_SUMMARY}
          echo "Scenario 5 conclusion: ${{ steps.scen-5.conclusion }}" >> ${GITHUB_STEP_SUMMARY}

    
