name: Summary Output Page Workshop

on:
  workflow_dispatch:

jobs:
  single_job_summary:
    name: Single Job Summary
    runs-on: ubuntu-latest
    steps:
      - name: Output Single Summary
        run: |
          echo "test1" >> test_file.txt
          echo "second line" >> test_file.txt
          echo "final line" >> test_file.txt
          echo "$(cat test_file.txt)" >> ${GITHUB_STEP_SUMMARY}
  matrix_job_summaries:
    name: Matrix Job Summaries
    runs-on: ubuntu-latest
    outputs:
      value_test: ${{ steps.output_test.outputs.value_test }}
    strategy:
      matrix:
        test_value: ['one', 'two', 'three']
    steps:
      - name: Matrix Summary Number ${{ matrix.test_value }}
        id: output_test
        run: |
          echo "Here is test_value ${{ matrix.test_value }}" >> ${GITHUB_STEP_SUMMARY}
          echo "value_test=test" >> ${GITHUB_OUTPUT}
  print_outputs:
    name: Matrix Outputs
    runs-on: ubuntu-latest
    needs: matrix_job_summaries
    steps:
      - name: Output Stuff
        run: echo '${{ needs.matrix_job_summaries.outputs.value_test }}'

