name: Summary Output Page Workshop

on:
  workflow_dispatch:

jobs:
  single_job_summary:
    name: Single Job Summary
    runs-on: ubuntu-latest
    steps:
      - name: Output Single Summary
        run: |
          echo "test1" >> test_file.txt
          echo "second line" >> test_file.txt
          echo "final line" >> test_file.txt
          echo "$(cat test_file.txt)" >> ${GITHUB_STEP_SUMMARY}
  matrix_job_summaries:
    name: Matrix Job Summaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_value: ['one', 'two', 'three']
    steps:
      - name: Matrix Summary Number ${{ matrix.test_value }}
        run: echo "Here is test_value ${{ matrix.test_value }}" >> ${GITHUB_STEP_SUMMARY}

